### ISSUE TITLE
Add "until done" label to Play Music Disc block?

### ISSUE THREAD

**Issue by Jaqster** [microsoft/makecode-minecraft-music#11]
Right now, I don't think there's any way to stop a music track once you start playing it.
To make this more clear to users, might be nice to add a "until done" label to the block - no drop-down.
![image](https://github.com/microsoft/makecode-minecraft-music/assets/22108954/aabf8200-babd-43af-8620-da3ef7c3733a)
![image](https://github.com/microsoft/makecode-minecraft-music/assets/22108954/c5cbb501-e7b3-49f1-b9ee-c54e7ebb7603)

**Comment by srietkerk** [comment]
I think if we add a label after the music dropdown, it should be "in background". If you use the "until done" option in the drop down in arcade, it will basically play the song and won't run any other code until the song is completely down. When playing a music disc in Minecraft, the code after it will run. I'm just not sure what value it would add to put the label afterwards.

**Comment by srietkerk** [comment]
As a follow-up, if the "stop all sounds" block does not work for music discs, that's a bug. The block configuration that's pictured should just not play any sound because the music is stopped right as it starts to play.

**Comment by Jaqster** [comment]
I think "in background" provides more helpful context to the user.  Thanks Sarah!
