### ISSUE TITLE
Pause does not work with 1 beat default when parameter his hidden

### ISSUE THREAD

**Issue by thsparks** [microsoft/makecode-minecraft-music#12]
I think when the pause parameter is hidden on a music block, it should pause for 1 beat (which is the default when the parameter is expanded), but it doesn't.

In other words, these two blocks should have the same behavior:
![image](https://github.com/microsoft/makecode-minecraft-music/assets/69657545/04b36a10-ab8c-4a90-96ad-7e3dcc0f1c06)

**Comment by srietkerk** [comment]
I remember chatting a bit about this on Friday, and thinking it was a bug, but now I'm almost thinking we should leave it the way that it is currently. 

I know it's not super helpful for the situation where teachers are trying to use these blocks to teach music, but I found it fun playing a bunch of instruments on top of each other and creating an interesting sound.

On the other hand, if we want the block to just always pause to remove that barrier when teaching, I think we should just make the block not expandable and have the pause for 1 beat always exposed.

**Comment by thsparks** [comment]
I think if people want the "play a bunch of sounds all at once" scenario, they should be able to set the pause to 0, but I don't think it'd be the default. My assumption is, if someone puts a bunch of these blocks one after the other, they'd expect them to play one after the other. So from my perspective, it makes sense to keep the expansion, but we should change unexpanded behavior to pause for 1 beat.
