### ISSUE TITLE
Make capitalization consistent in music disc dropdown

### ISSUE THREAD

**Issue by kimprice** [microsoft/makecode-minecraft-music#14]
See pic below, the last item has capitalization that is inconsistent with the ones above. If this is consistent with how Minecraft labels it, then keep it the same.
![image](https://github.com/microsoft/makecode-minecraft-music/assets/15070078/96f34385-0db9-4f25-8a38-8a78ea497b2a)

**Comment by srietkerk** [comment]
Yeah, I think this is just how the song titles are capitalized, even though it looks a bit weird. If you take a look at the disc wiki, the different songs just have those capitalizations: https://minecraft.fandom.com/wiki/Music_Disc.
